name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Poetry
        uses: abatilo/actions-poetry@v2.0.0
      
      - name: Open Poetry shell
        run: poetry shell
      
      - name: Install dependencies
        run: poetry install

      - name: make all
        run: make
